# $$NumPy$$

- NumPy is a library - Numerical Python
- Helps us in all sorts of numerical operations
- a Mathematics library
- to install you need the package in your system
- 
- you use the pip module to do that ---  a module within our python interpreter
- pip helps us install libraries

```markdown
- pip install lib_name ---> installs in your environment
- %pip install lib_name ---> Magic command ---> it installs in the current kernal --- sometimes might need to install later again --- depending on your working method
- !pip install lib_name ---> It directly installs using Terminal - your global python environment gets the package

- NumPy helps us create ndarrays ---> N - Dimensional Array
- 
- 

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

array_1d = np.array([1,2,3,4,5])

# single dimension array

type(array_1d) # numpy.ndarray

### Why do we need them

In a list, you can store multiple types of data but we cannot do that in arrays
- Storing sequential data ---> one after the other
- 
- Python does not have a built-in `array` type like some other languages
    - `array is a linear data structure that saves data sequentially`
- similar functionality and working in python can be achieved using:
    1. **Lists** 
        - Lists are a `flexible` and `commonly used` data structure for storing elements in sequence
        - allow mixing data types - `heterogenous`
        - other languages only have arrays, and they do not allow mixing types
    2. **Array module** - 
        - does allow creation of arrays
        - these are faster than lists as well
        - you have to remember stuff like `i` represents `int`
    3. **NumPy arrays** -
        - built with Numpy library

In [ ]:
import array as arr

a = arr.array('i', [1, 2, 3])

# in array package, you have to declare what type of data you are saving before hand
# 'i' represents integer type

#### Array 
- a data structure to save elements sequentially 
- properties:
    - saved in `contigous` memory locations (one after the other)
    - `HOMOGENOUS` - Can save only a single type of data (unlike lists)
    - faster and more memory efficient than lists
- 
- we gain massive performance instead of having flexibility
- 

#### Arrays VS Lists
- faster and more memory efficient than lists
- 
- In Lists 
    - you have a `python object` and it has its own memory overhead
    - Lists store memory addresses (pointers)
    - When accessing an element, follow pointers that are `scattered` across the RAM
    - This means `more memory used` and `less speed` in getting data in comparison to Homogenous structures like Arrays
- 
- In arrays:
    - You store `actual data`
    - No following the pointers
    - no extra memory overhead, because you exactly know how much space to allocate before time - Pack data tightly
    - Superior performance in comparison
    - 
    - Broadcasting can be done here ---> because of which Matrix Multiplication (`a @ b`)  is possible
        - a very important operation because we can solve equations because of it


---

##### NumPy Array 
- 

In [ ]:
import numpy as np

# single dimensional array
array_1d = np.array([1,2,3,4,5])

# Two dimensional array
array_2d = np.array([[1, 2, 3, 4, 5 ],
                     [10,20,30,40,50]])

# Two dimensional array
array_2d = np.array([[1, 2, 3, 4, 5,],
                     [10,20,30,40,50],
                     [11,22,33,44,55]])

# Three dimensional array
array_3d = np.array([
                    [[1, 2, 3, 4, 5,],
                     [10,20,30,40,50],
                     [11,22,33,44,55]],
                     
                     [[1, 2, 3, 4, 5,],
                     [10,20,30,40,50],
                     [11,22,33,44,55]]
])

type(array_2d) # numpy.ndarray
print(array_3d)

print(array_3d.ndim)

We can manually set up the precision
- 

In [ ]:
list_2d = [[100, 2, 3, 4, 5 , 45, 77], [10,20,30,40,50]]

print(list_2d)

In [42]:
int_array = np.array(
    [1,2,3]
)

# int_array = np.array([1,2,3, 3.14]) # dtype('float64')

int_array.dtype

dtype('int64')

In [40]:
str_array = np.array(
    ["idrees","1,2,3"]
)
str_array.dtype

dtype('<U6')

In [ ]:
newarray = np.array(
    [1,2,3,"idrees",3.14]
)

newarray.dtype

dtype('<U32')

### Exercise:  (understand performance difference between the tow)

1. Create a python List ---> `N = 10000` then `listname = list(range(N))`
2. Create an numpy array
3. We observe the size of both ---> use the `sys` module and `sys.getsizeof()`
4. Use time module to time the amount of time taken to do multiplication
    - `start_time = time.time() # current time`
    - your list *2 ---> execute this 
    - end_time = time.time()
    - list_time = end_time - start_time ---> amount of time took for a list to multiply 2 with all the members
5. Repeat the step 4 with a array - But simply multiply the array with the list

If not much difference please increase `N` to 1000000000

In [ ]:
import sys

listname = [1,99999999999999999999]

# single number - 0 -> 28
# empty list = 56 B
# 1 int, 64 B
# for each new place --> 8 Bytes for each new element


print(f"{sys.getsizeof(listname)} bytes")

72 bytes


In [ ]:
listname = [
            0,                       # 28 B
            1,                       # 28 B
            100,                     # 28 B
            268435455,               # 28 B
            747_477_474_783_839,     # 32 B
            10**50 # 1 with 50 zeros # 48 B
            ]

for num in listname:
    size = sys.getsizeof(num)
    print(f"number is: {num}")
    print(f"size is: {size}")

print(f"Total list size: {sys.getsizeof(listname)} bytes")

number is: 0
size is: 28
number is: 1
size is: 28
number is: 100
size is: 28
number is: 268435455
size is: 28
number is: 536870911
size is: 28
number is: 747477474783839
size is: 32
number is: 100000000000000000000000000000000000000000000000000
size is: 48
Total list size: 112 bytes


In [32]:
import numpy as np

array_name = np.array([
            0,
            1,
            100,
            6553
            #747_477_474_783_839,
            #10**50 # 1000000 50 zeros
            ], dtype = np.int16)

# every single element only gets 16 bytes of memory

for num in array_name:
    size = sys.getsizeof(num)
    print(f"number is: {num}")
    print(f"size is: {size}")

print(f"Total list size: {sys.getsizeof(array_name)} bytes")

number is: 0
size is: 26
number is: 1
size is: 26
number is: 100
size is: 26
number is: 6553
size is: 26
Total list size: 120 bytes


Precision
- how much you want to keep to store a number
- int16 ---> 2 bytes 


In [33]:
import time
import sys
import numpy as np

N = 10_000_000
my_list = list(range(N)) # -----

# NumPy array (16-bit signed integer)
my_numpy = np.arange(N, dtype=np.int16)

# without declaring dtype or size of
my_numpy2 = np.array(range(N))

# Get the size of both containers in bytes
list_size = sys.getsizeof(my_list)
array_size = sys.getsizeof(my_numpy)
array_size2 = sys.getsizeof(my_numpy2)

print(f"Elements stored: {N:,}")
print("-" * 30)
print(f"Python List Size: {list_size:,} bytes")
print(f"Numpy array with arrange method and dtype: {array_size:,} bytes")
print(f"Numpy array with RANGE method Size: {array_size2:,} bytes")


#-------------------
print("="*30)
#--------------------

# operation with list
start_time = time.time()
list1 = [i*2 for i in my_list]
end_time = time.time()
 
list_time = end_time - start_time

# operation with array
start_time = time.time()
my_numpy = my_numpy * 2
end_time = time.time()
 
array_time = end_time - start_time
print(f"List Time: {list_time:.2f}, Array Time: {array_time:.2f}")

Elements stored: 10,000,000
------------------------------
Python List Size: 80,000,056 bytes
Numpy array with arrange method and dtype: 20,000,112 bytes
Numpy array with RANGE method Size: 80,000,112 bytes
List Time: 1.11, Array Time: 0.02


In [ ]:
print(my_numpy.dtype)
print(my_numpy2.dtype)

#### Properties of Numpy Arrays
- `array_name.ndim` -> number of dimensions 
- `array_name.shape` -> finds the `shape` or actual dimension ---> shape = (rows , cols) of an array
- `array_name.size` - how many elements
- `array_name.dtype` - 

- ROW Vector
    - single dimension

In [ ]:
array_1d = np.array([1,2,3,4,5])

array_1d.shape # [ 1 2 3 4 5]
# row vector --- row matrix 
# 1 row, 0 columns
# shown as (5,)
array_1d.ndim

- COLUMN Vector
    - In maths these are single dimension
    - In Numpy treated as two dimension

In [36]:
array_1d = np.array([[1],[2],[3],[4],[5]])

array_1d.shape # [ 1 2 3 4 5]
# row vector --- row matrix 
# 1 row, 0 columns
# shown as (5,)
array_1d.ndim
array_1d.shape
array_1d.size
array_1d.dtype

dtype('int64')

#### Methods of Numpy Arrays

- Common methods of creation of arrays
- 

In [84]:
a = np.arange(10) # uses the range like object
a = np.arange(10, 50, 2) # start end step

a = np.array_split(a, 3) # pass an array, and how many parts you want to get

# linspace ---> creates a Evenly spaced linear array
# inclusive of both numbers starting and ending
a = np.linspace(0, 10, 10) # go from 0 to 1, in 10 steps

a = np.zeros((2,3)) # pass a shape in
a = np.ones((5,3)) # pass a shape in

# Random numbers ---> need the random module
# for reproduceabilty of results
np.random.seed(42)

a = np.random.rand(5,3) # random number of the shape
# these numbers are all <1

# pass the range you wish and the shape
a = np.random.randint(0, 100, (3,3)) # numbers in a specified range


print(a)

[[20 32 75]
 [57 21 88]
 [48 90 58]]


#### Operations of Numpy Arrays

In [ ]:
# OPTIONAL
# SOLVING AN EQUATION

a = np.array([
    [10, 2],
    [20, 4]
])

x, y = 0, 0

b = np.array([[x], 
              [y]] # (2, 1) ---> 2 rows, 1 column
) 

b.shape


a @ b # ---> Matrix Multiplication
